<?php

/**
 * Implements hook_theme().
 */
function cohesion_devel_theme($existing, $type, $theme, $path) {
  return [
    'stylesheet_inspector' => [
      'variables' => ['data' => []],
    ],
    'sass_variables' => [
      'variables' => ['colours' => []],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 * @param array $attachments
 */
function cohesion_devel_page_attachments(array &$attachments) {

  $is_admin = \Drupal::service('router.admin_context')->isAdminRoute();
  $config = \Drupal::configFactory()->getEditable('cohesion_devel.settings');

  // Hide all errors and warnings?
  $status = $config->get("supress_errors_and_warnings");
  if ($status && $is_admin) {
    $attachments['#attached']['library'][] = 'cohesion_devel/hide-errors-warnings';
  }

}

/**
 * Implements hook_library_info_alter().
 *
 * @param $libraries
 * @param $extension
 * @return void
 */
function cohesion_devel_library_info_alter(&$libraries, $extension) {
  $cohesion_dev_path = 'cohesion-services/dx8-gateway/assets/dx8/scripts/app.js';
  if (
    isset($libraries['cohesion-admin-scripts']) &&
    file_exists(\Drupal::service('extension.path.resolver')->getPath('module', 'cohesion') . '/' . $cohesion_dev_path)) {

    // Get relative path from stream wrapper.
    $path = \Drupal::service('file_url_generator')->generateString('public://cohesion/scripts/dx8/app.js');

    // Load the app.js directly from the cohesion-services directory.
    unset($libraries['cohesion-admin-scripts']['js'][$path]);
    $libraries['cohesion-admin-scripts']['js'][$cohesion_dev_path] = ['minified' => true];

  }
}
